---
title: "clutsering for Eric"
output: html_notebook
---
```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, collapse = T)
knitr::opts_chunk$set(message = F)
knitr::opts_knit$set(root.dir = '.')
```

# Setup:
## loading
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggsci)
  library(ggpubr)
  library(ggsignif)
  library(ggthemes) 
  library(ggrepel)
  library(ggforce)
  library(extrafont)
  library(ggrepel)
  library(pheatmap)
  library(viridis)
  library(patchwork)
  library(matrixStats)
})
suppressMessages(loadfonts())
```
## setting ggplot theme
```{r}
theme_set(theme_foundation(base_size = 7,
                           base_family = 'Helvetica') + 
            theme(plot.title = element_blank(),
                panel.background = element_rect(colour = NA),
                plot.background = element_rect(colour = NA),
                panel.border = element_rect(colour = NA),
                axis.title = element_text(face = "bold",size = rel(1)),
                axis.title.y = element_text(angle=90,vjust =2),
                axis.title.x = element_text(vjust = -0.2),
                axis.text = element_text(size = rel(1)), 
                axis.line = element_blank(),
                strip.text = element_text(size = rel(1)),
                strip.background = element_blank(),
                legend.key.size= unit(0.08, "in"),
                legend.spacing = unit(0, "in"),
                legend.key = element_rect(colour = NA),
                legend.title = element_text(face="italic"),
                legend.text = element_text(face = 'bold'),
                plot.margin=margin(0.04,
                                   0.04,
                                   0.04,
                                   0.04,
                                   unit = "in"),
                legend.margin = margin(-0.04,
                                   -0.02,
                                   -0.08,
                                   -0.01,
                                   unit = "in"),
                legend.box.spacing = unit(-0.02, 'in'),
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank()
          ))

panel.figure.width = 3.32
panel.figure.height = 2

panel.save <- function(figure, name, width = 'single', height = 'single'){
  
  if (width == 'single'){
    panel.width = panel.figure.width
  } else{
    panel.width = panel.figure.width*2
  }
  
  if (height == 'single'){
    panel.height = panel.figure.height
  } else{
    panel.height = panel.figure.height*2
  }
  
  ggsave(paste0(figure.dir.exotic, 
                'fig.',
                figure,
                '/', 
                name, 
                '.',
                panel.width, 
                'x', 
                panel.height, 
                '.pdf'),
       width = panel.width, 
       height = panel.height, 
       units = 'in')
}
```
# load data
```{r}
fpkm <- read_tsv('../scripts/FPKM_normalized_coverages.tsv')
tpm <- read_tsv('../scripts/TPM_normalized_coverages.tsv')
library_norm <- read_tsv('../scripts/Library_normalized_coverages.tsv')

lib_names <- read_csv('../scripts/atac_libnames.txt', col_names = c('sample','lib'))

profile_gene_overlap <- 
  read_tsv('../scripts/profile_gene_overlap.bed', col_names = c('chr','start','end')) %>% 
  unite('coord', c('chr', 'start'), sep = ':') %>% 
  unite('coordinate', c(coord, end), sep = '-')

expression_overlap_promoters <- 
  read_tsv('../scripts/expression_overlap_promos_new.bed', col_names = c('chr','start','end', 'junk')) %>% 
  select(-junk) %>% 
  unite('coord', c('chr', 'start'), sep = ':') %>% 
  unite('coordinate', c(coord, end), sep = '-') %>% 
  mutate(coordinate = str_trim(coordinate))

batch_names <- 
  read_tsv('../scripts/batch_label_libname.txt') %>% 
  merge(lib_names, by.x = 'libname', by.y = 'lib') %>% 
  unite('sample', c('sample', 'libname'), sep = '-') %>% 
  separate(sample, sep = '_', into = c('sample', NA))
```
# for sree
```{r}
day.7.de.seq %>% 
  filter(gene %in% filter(gen.34.lnc.te.overlap, grepl('HERVH|LTR7', te))$gene) %>% 
    ggplot(aes(log2FoldChange, -log10(padj))) +
      geom_point(alpha = 0.6) + 
      geom_rug(size = rel(1), alpha = 0.6) + 
      # scale_x_continuous(limits = c(-x.max,x.max), expand = c(0,0.5),
      #                    breaks = c(-x.max, -x.max/2, -1, 0, 1, x.max/2, x.max)) +
      scale_color_viridis_c() +
      xlab('log2FoldChange') +
      ylab('-log10(FDR)') + 
      geom_text_repel(aes(label = ifelse(log2FoldChange >= 2 & !grepl('^A', gene), gene, '')),
                          box.padding = unit('0.8', 'lines'),
                              segment.color = 'grey',
                              segment.alpha = 0.2,
                              color = 'black',
                              ylim = c(2.0, Inf), size = rel(2.5))
panel.save(1, 'for.sree.herv.and.ltr7.lncrna.day.7', width = 'double', height = 'single')

day.7.de.seq %>% 
  filter(gene %in% ras.markers$gene) %>% 
      ggplot(aes(log2FoldChange, -log10(padj), label = gene)) +
      geom_point(alpha = 0.6) + 
      geom_rug(size = rel(1), alpha = 0.6) + 
      # scale_x_continuous(limits = c(-x.max,x.max), expand = c(0,0.5),
      #                    breaks = c(-x.max, -x.max/2, -1, 0, 1, x.max/2, x.max)) +
      scale_color_viridis_c() +
      xlab('log2FoldChange') +
      ylab('-log10(FDR)') + 
      geom_text_repel(aes(label = ifelse(gene %in% c('NFKB1', 'FOS', 'ETS1'), gene, '')),
                      box.padding = unit('0.8', 'lines'),
                              segment.color = 'grey',
                              segment.alpha = 0.2,
                              color = 'black',
                              ylim = c(2.0, Inf), size = rel(3))
panel.save(1, 'for.sree.kras.tfs.day.7', width = 'single', height = 'single')

day.7.de.seq %>% 
  merge(neuro.markers, by = 'gene') %>% 
      ggplot(aes(log2FoldChange, -log10(padj), label = gene)) +
      geom_point(alpha = 0.6) + 
      geom_rug(size = rel(1), alpha = 0.6) + 
      # scale_x_continuous(limits = c(-x.max,x.max), expand = c(0,0.5),
      #                    breaks = c(-x.max, -x.max/2, -1, 0, 1, x.max/2, x.max)) +
      # scale_color_viridis_d() +
      xlab('log2FoldChange') +
      ylab('-log10(FDR)') + 
      geom_text_repel(aes(label = ifelse(gene %in% c('NEUROG1', 'PRDM12', 'NEUROD1', 'NEUROD4'), gene, '')),
                      box.padding = unit('0.8', 'lines'),
                              segment.color = 'grey',
                              segment.alpha = 0.2,
                              color = 'black',
                              ylim = c(2.0, Inf), size = rel(3))

panel.save(1, 'for.sree.neuro.markers.day.7', width = 'single', height = 'single')
  
```

# 
```{r}

filtered.fpkm <- 
  tpm %>% 
  filter(coordinate %in% expression_overlap_promoters$coordinate) %>% 
  # mutate(sd = rowSds(as.matrix(.[,-c(1)]))/rowMeans(.[,-c(1)])) %>%
  # top_frac(0.5, sd) %>%
  gather(lib, counts, -coordinate) %>% 
  merge(lib_names) %>% 
  unite('sample', c('sample', 'lib'), sep = '-') %>% 
  separate(sample, sep = '_', into = c('sample', NA)) %>% 
  mutate(counts = log(counts + 1)) %>% 
  # select(coordinate, sample, counts, -lib) %>% 
  pivot_wider(names_from = sample, values_from = counts)

pheatmap(filtered.fpkm %>% column_to_rownames('coordinate'), 
         show_rownames = F, 
         color = viridis(20))
```

```{r}
### Gencode PCA
tx.condition.mapping.volume.pca <-  
  filtered.fpkm %>%
  column_to_rownames('coordinate') %>% 
  t() %>% 
  as.data.frame() %>% 
  prcomp(scale=T)

summary(tx.condition.mapping.volume.pca)
pcs.of.interest <- apply(tx.condition.mapping.volume.pca$x, 2, var)
pcs.props <-  pcs.of.interest/sum(pcs.of.interest)
cumsum(pcs.props)[1]
 
# convert output to dataframe
pca.out <- 
  as.data.frame(tx.condition.mapping.volume.pca$x) %>% 
  rownames_to_column('sample') %>% 
  separate(sample, sep = '-', into = c('sample', NA))

# summarize PC contributions
pca.out.summary <- 
  as.data.frame(summary(tx.condition.mapping.volume.pca)$importance) %>% 
  rownames_to_column('metric') %>% 
  gather(pc, value, -metric) %>% 
  spread(metric, value)
# summarize PC contributions
pca.out.contributions <- 
  as.data.frame(tx.condition.mapping.volume.pca$rotation) %>% 
  rownames_to_column('tx') %>% 
  gather(pc, contrib, -tx) %>% 
  #merge(gencode.reference,
  #      by.x = 'tx',
  #      by.y = 'gene.name') %>% 
  group_by(pc) %>% 
  mutate(contrib = abs(contrib)) %>% 
  filter(contrib > quantile(contrib, 0.95))

# plot PC1 and PC2
pca.out %>% 
  #rownames_to_column('sample') %>% 
  #separate(sample, sep = '[.]', into = c(NA, 'condition', NA)) %>% 
  ggplot(aes(PC1, PC2, 
             color = sample,
             label=sample)) + 
    geom_text(size = rel(5)) + 
    xlab(paste('PC1', round(cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
    ylab(paste('PC2', round(cumsum(pcs.props)[2] - cumsum(pcs.props)[1], 
                            digits = 3), sep = ' ')) +
    scale_color_viridis_d() + 
    geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) +
    geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) + 
    theme(legend.position = 'right',
            legend.key.width = unit(0.125,'cm'),
            legend.key.height = unit(0.4, 'cm'))
```
# batch effect
```{r}
library(sva)


pheno <- batch_names
edata <- data.matrix(filtered.fpkm %>% select(-coordinate))
batch <- pheno$s_batch

# parametric adjustment
combat_edata1 = ComBat(dat=edata, batch=batch, mod=NULL, par.prior=TRUE, prior.plots=FALSE)

combat_edata1 %>% 
  as.data.frame() %>% 
  cbind(filtered.fpkm %>% select(coordinate)) %>% 
  # mutate(sd = rowSds(as.matrix(.[,-c(27)]))/rowMeans(.[,-c(27)])) %>%
  # top_frac(0.35, sd) %>%
  # select(-sd) %>% 
  column_to_rownames('coordinate') %>% 
  pheatmap(show_rownames = F, 
         color = viridis(20))
  
```
```{r}
### Gencode PCA
tx.condition.mapping.volume.pca <-  
  combat_edata1 %>%
  as.data.frame() %>% 
  cbind(filtered.fpkm %>% select(coordinate)) %>% 
  column_to_rownames('coordinate') %>% 
  t() %>% 
  as.data.frame() %>% 
  prcomp(scale=T)

summary(tx.condition.mapping.volume.pca)
pcs.of.interest <- apply(tx.condition.mapping.volume.pca$x, 2, var)
pcs.props <-  pcs.of.interest/sum(pcs.of.interest)
cumsum(pcs.props)[1]
 
# convert output to dataframe
pca.out <- 
  as.data.frame(tx.condition.mapping.volume.pca$x) %>% 
  rownames_to_column('sample') %>% 
  separate(sample, sep = '-', into = c('sample', NA))

# summarize PC contributions
pca.out.summary <- 
  as.data.frame(summary(tx.condition.mapping.volume.pca)$importance) %>% 
  rownames_to_column('metric') %>% 
  gather(pc, value, -metric) %>% 
  spread(metric, value)
# summarize PC contributions
pca.out.contributions <- 
  as.data.frame(tx.condition.mapping.volume.pca$rotation) %>% 
  rownames_to_column('tx') %>% 
  gather(pc, contrib, -tx) %>% 
  #merge(gencode.reference,
  #      by.x = 'tx',
  #      by.y = 'gene.name') %>% 
  group_by(pc) %>% 
  mutate(contrib = abs(contrib)) %>% 
  filter(contrib > quantile(contrib, 0.95))

# plot PC1 and PC2
pca.out %>% 
  #rownames_to_column('sample') %>% 
  #separate(sample, sep = '[.]', into = c(NA, 'condition', NA)) %>% 
  ggplot(aes(PC1, PC2, 
             color = sample,
             label=sample)) + 
    geom_text(size = rel(5)) + 
    xlab(paste('PC1', round(cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
    ylab(paste('PC2', round(cumsum(pcs.props)[2] - cumsum(pcs.props)[1], 
                            digits = 3), sep = ' ')) +
    scale_color_viridis_d() + 
    geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) +
    geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) + 
    theme(legend.position = 'right',
            legend.key.width = unit(0.125,'cm'),
            legend.key.height = unit(0.4, 'cm'))
```


