---
title: "ATAC paper #2 Martin et al"
author: 'Roman E. Reggiardo'
date: '1/20/2020'
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, collapse = T)
knitr::opts_chunk$set(message = F)
library(here)
print(here())
```

# setup:
## loading
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggsci)
  library(ggpubr)
  library(ggsignif)
  library(ggthemes) 
  library(ggrepel)
  library(ggforce)
  library(extrafont)
  library(ggrepel)
  library(pheatmap)
  library(viridis)
  library(patchwork)
  library(fgsea)
  library(caret)
  library(msigdbr)
  library(matrixStats)
  library(NMF)
  library(rsample)
  library(vip)
  library(ROCR)
  library(glmnet)
  library(mlbench)
  library(tximeta)
  library(SummarizedExperiment)
  library(rjson)
  library(HDF5Array)
  library(DESeq2)
  library(ggpmisc)
})
suppressMessages(loadfonts())
```
## figure dirs, and other globally relevant constants
```{r}
figure.dir <-  here('figures')
data.dir <-  here('data')
output.data.dir <- here('output.data')
reference.dir <- here('reference')

chr.order <- c('chr1', 'chr2', 'chr3', 
               'chr4', 'chr5', 'chr6', 
               'chr7', 'chr8', 'chr9',
               'chr10', 'chr11', 'chr12', 
               'chr13', 'chr14', 'chr15', 
               'chr16', 'chr17',
               'chr18', 'chr19', 'chr20', 
               'chr21', 'chr22', 'chrX', 'chrY')

cell.type.order <- c('HSC', 'MPP', 'CMP', 'GMP', 'GM', 'MEP', 
                     'MkP', 'EP', 'CLP', 'ProB', 'B', 
                     'ProT', 'T')

cell.type.color.palette <- c('#000000', '#7F7F7F', '#800002', '#F98D08', 
  '#FDA408', '#FA006B', '#FF00FF', '#FB0006', '#0F81ED', '#002CE5', '#0000FF', 
  '#16ADA9', '#00EEC7')

myeloid <- c('CMP', 'MEP', 'GMP', 'MkP', 'EP', 'GM')
lymphoid <- c('CLP', 'ProB', 'ProT', 'B', 'T')
```
## saving panels
```{r}
panel.figure.width = 4
panel.figure.height = 2.44

panel.save <- function(figure, name, width = 'single', height = 'single'){
  
  if (width == 'single'){
    panel.width = panel.figure.width
  } else{
    panel.width = panel.figure.width*2
  }
  
  if (height == 'single'){
    panel.height = panel.figure.height
  } else if (height == 'half'){
    panel.height = panel.figure.height/2
  } else{
    panel.height = panel.figure.height*3
  }
  
  ggsave(paste0(output.data.dir, 
                '/',
                'eric.atac',
                '/', 
                name, 
                '.',
                panel.width, 
                'x', 
                panel.height, 
                '.pdf'),
       width = panel.width, 
       height = panel.height, 
       units = 'in')
}

save_pheatmap_pdf <- function(x, filename, width=5, height=3) {
   stopifnot(!missing(x))
   stopifnot(!missing(filename))
   pdf(filename, width=width, height=height)
   grid::grid.newpage()
   grid::grid.draw(x$gtable)
   dev.off()
}
```

# chromvar counts
```{r}
final.peaks <- read_tsv(file.path(output.data.dir, 
                                 'eric.atac', 'final_peaks_0622.txt'))

peak.annotations <- read_tsv(file.path(output.data.dir, 
                                 'eric.atac', 'final_peaks_0622_anno.txt')) %>% 
  rename(Chr = 'chr', Start = 'start', End = 'end', Annotation = 'annotation', 'Gene Name' = 'gene')

chromvar.counts <- get(load(file.path(output.data.dir, 
                                 'eric.atac', 'this_one_filtered_counts_0622.Rdata')))


hsc_peaks <- read_tsv(file.path(output.data.dir, 
                                    'eric.atac', 
                                    'hsc_overlap_u.bed'),
                      col_names = c('chr', 
                                    'start',
                                    'end',
                                    'idk'))

mpp_peaks <- read_tsv(file.path(output.data.dir, 
                                    'eric.atac', 
                                    'mpp_overlap_u.bed'),
                      col_names = c('chr', 
                                    'start',
                                    'end',
                                    'idk'))

chromvar.counts@colData %>% 
  as.data.frame() %>% 
  rownames_to_column('sample') %>% 
  mutate(batch = sample) %>% 
  separate(batch, sep = '_', into = c('batch', NA, NA, NA, NA, NA)) %>% 
  mutate(lineage = ifelse(celltype %in% myeloid, 'myeloid', 
                          ifelse(celltype %in% lymphoid, 
                                 'lymphoid', 'multi-potent'))) %>% 
    column_to_rownames('sample')-> chromvar.col.data

rowRanges(chromvar.counts) %>% 
  as.data.frame() %>% 
  rename(seqnames = 'chr') %>% 
  merge(peak.annotations %>% 
          mutate(start = start - 1) %>% 
          select(chr, start, end, gene, annotation), 
        by = c('chr', 'start', 'end')) %>% 
  select(-width, -strand, -bias) -> chromvar.peaks

assay(chromvar.counts, 'counts') %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  cbind(chromvar.peaks) %>% 
  gather(sample, count, -chr:-annotation) %>% 
  merge(chromvar.col.data %>% 
          select(-depth, -lineage) %>% 
          rownames_to_column('sample') %>% 
          unite('sample_1', sep = '_', c(celltype, batch)), 
        by = 'sample') %>% 
  select(-sample) %>%
  spread(sample_1, count) -> chromvar.counts.wide


chromvar.col.data %>% 
  select(-depth) %>% 
  rownames_to_column('sample') %>%
  mutate(cell.type = celltype) %>% 
  unite('sample_1', sep = '_', c(celltype, batch)) %>% 
  select(-sample) %>% 
  column_to_rownames('sample_1') -> chromvar.col.data
  

chromvar.counts.wide %>%
  # filter(grepl('non-coding', annotation)) %>%
  select(contains('_')) %>%
  mutate_if(is.numeric, list(~scale(log(. + 1)))) %>%
  # filter_at(vars(contains('_')), all_vars(. > 100)) %>%
  cor(method = 'spearman') %>% pheatmap(annotation_row = chromvar.col.data %>% select(-cell.type),
                     annotation_col = chromvar.col.data %>% select(-cell.type))
# 
# chromvar.counts.wide %>% 
#   unite('peak', sep = '_', c('chr', 'start', 'end', 'gene', 'annotation')) %>% 
#   filter(grepl('TSS', peak)) %>%
#   column_to_rownames('peak') %>%
#   # filter_at(vars(contains('_')), any_vars(abs(.) >= 20)) %>%
#   mutate_if(is.numeric, list(~scale(log(. + 1)))) %>% 
#   t() %>% as.data.frame() %>% 
#   pheatmap(show_colnames = F,
#            show_rownames = T,
#            annotation_row = chromvar.col.data %>% select(-cell.type)) 
```

```{r}


colnames(cqn.counts$counts) %>% 
  as.data.frame() %>%
  rename('.' = 'cell.type') %>% 
  mutate(old.name = cell.type) %>% 
  separate('cell.type', sep = '_', into = c('cell.type', 'batch')) %>% 
  mutate(cell.type = ifelse(cell.type %in% c('ProB', 'ProT'), 
                            cell.type, toupper(cell.type))) %>% 
  mutate(cell.type = ifelse(cell.type == 'MKP', 'MkP', cell.type)) %>% 
  mutate(lineage = ifelse(cell.type %in% myeloid, 'myeloid', 
                          ifelse(cell.type %in% lymphoid, 
                                 'lymphoid', 'progenitor'))) %>% 
  unite('cell.type', sep = '_', c(cell.type, batch)) -> col.data


chromvar.col.data %>% 
  rownames_to_column('sample') %>% 
  merge(col.data %>% separate('cell.type', sep = '_', into = c('celltype', 'batch')), by = 'celltype') -> 
  chromvar.col.data

assay(chromvar.counts, 'counts') %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  gather(sample, count) %>% 
  merge(chromvar.col.data, by = 'sample') -> chromvar.counts.tidy

chromvar.counts.tidy %>% 
  # unite('cell.type', sep = '_', c(celltype, sample)) %>% 
  select(-old.name, -lineage, -depth) %>% 
  unstack(count~sample) %>% 
  as.data.frame() %>% distinct() -> chromvar.counts.wide

cqn.counts$counts %>% 
  cbind(final.peaks) %>% 
  gather(old.name, count,  -seqnames, -start, -end, -width, -strand, -bias) %>% 
  merge(col.data, by = 'old.name') %>% 
  select(-old.name) %>% 
  distinct() -> cqn.counts.tidy


cqn.counts.tidy %>% 
  select(-lineage) %>% 
  # mutate(count = log(count + 1),
  #      count = scale(count, center = T)) %>% 
  spread(cell.type, count) %>% 
  select(-seqnames, -strand, -bias)  -> cqn.counts.wide

cqn.counts.wide %>% 
  select(contains('_')) %>% 
  # filter_at(vars(contains('_')), all_vars(. > 100)) %>%
  cor() %>% pheatmap(annotation_row = col.data %>% column_to_rownames('cell.type') %>% select(-old.name),
                     annotation_col = col.data %>% column_to_rownames('cell.type') %>% select(-old.name))

cqn.counts.wide %>% 
  unite('peak', sep = '_', c('start', 'end', 'width')) %>% 
  column_to_rownames('peak') %>%
  filter_at(vars(contains('_')), any_vars(abs(.) >= 0.5)) %>%
  t() %>% as.data.frame() %>% 
  pheatmap(show_colnames = F, 
           annotation_row = col.data %>% column_to_rownames('cell.type') %>% select(-old.name))

chromvar.counts.wide %>% 
  # filter_at(vars(contains('_')), any_vars(. >= 10)) %>%
  cor() %>% pheatmap(show_rownames = F, show_colnames = F, 
                     annotation_row = chromvar.col.data %>% 
                       select(sample, lineage) %>% 
                       distinct() %>% column_to_rownames('sample'),
                     annotation_col = chromvar.col.data %>% 
                       select(sample, lineage) %>% 
                       distinct() %>% column_to_rownames('sample'))

chromvar.col.data %>% 
                       select(sample, lineage) %>% 
                       distinct() %>% column_to_rownames('sample')


rownames(chromvar.col.data %>% select(sample, lineage.x) %>% distinct() %>% column_to_rownames('sample'))

colnames(chromvar.counts.wide)

chromvar.counts.wide %>% 
  # unite('peak', sep = '_', c('start', 'end', 'width')) %>% 
  mutate(peak = row_number()) %>% 
  column_to_rownames('peak') %>%
  filter_at(vars(contains('_')), all_vars(abs(.) >= 1)) %>% as.data.frame() %>%
  mutate(id = row_number()) %>% 
  column_to_rownames('id') %>% 
  # t() %>%
  pheatmap(show_rownames = F, 
           annotation_row = col.data %>% column_to_rownames('cell.type') %>% select(-old.name),
           annotation_col = col.data %>% column_to_rownames('cell.type') %>% select(-old.name))

cqn.counts$counts %>% 
  filter_at(vars(contains('_')), all_vars(. >= 10)) %>%
  cor() 


```

```{r}
set.seed(234)
### Gencode PCA
chromvar.counts.wide %>% 
  # filter(grepl('non-coding', annotation)) %>% 
  unite('peak', sep = '_', c('chr','start', 'end', 'gene', 'annotation')) %>%
  mutate_if(is.numeric, list(~scale(log(. + 1)))) %>% 
  # filter_at(vars(contains('_')), any_vars(. >= 50)) %>%
  mutate(peak.cv = rowSds(as.matrix(select(., contains('_'))))) %>%
  filter(peak.cv > median(peak.cv)) %>%
  select(-peak.cv) %>%
  column_to_rownames('peak') %>%
  t() %>%
  as.data.frame() %>%
  prcomp() -> peak.pca

summary(peak.pca)
pcs.of.interest <- apply(peak.pca$x, 2, var)
pcs.props <-  pcs.of.interest/sum(pcs.of.interest)
cumsum(pcs.props)[c(1,2)]

as.data.frame(pcs.props) %>% 
  rownames_to_column('pc') %>% 
  mutate(pc = as.numeric(sub('PC', '', pc))) %>% 
  ggplot(aes(pc, pcs.props)) + 
  geom_col()
 
# convert output to dataframe
pca.out <- as.data.frame(peak.pca$x) %>% 
  rownames_to_column('sample')

# summarize PC contributions
pca.out.summary <- 
  as.data.frame(summary(peak.pca)$importance) %>% 
  rownames_to_column('metric') %>% 
  gather(pc, value, -metric) %>% 
  spread(metric, value)
# summarize PC contributions
pca.out.contributions <- 
  as.data.frame(peak.pca$rotation) %>% 
  rownames_to_column('tx') %>% 
  gather(pc, contrib, -tx) %>% 
  group_by(pc) %>% 
  #merge(gencode.reference,
  #      by.x = 'tx',
  #      by.y = 'gene.name') %>% 
  group_by(pc) %>% 
  mutate(contrib = abs(contrib),
         rel.contrib = contrib/sum(contrib))

# plot PC1 and PC2
pca.out %>% 
  merge(chromvar.col.data %>% rownames_to_column('sample'), by = 'sample') %>%
  mutate(cell.type = factor(cell.type, levels = cell.type.order)) %>% 
  # separate(cell.type, sep = '_', into = c('cell.type', 'batch')) %>%
  ggplot(aes(PC1, PC2, color = cell.type, #shape = lineage, 
             label = cell.type)) + 
    geom_point(size = rel(2), alpha = 1) + 
    # scale_size_continuous(range = c(0.1, 2.5), breaks = c(0,5,10,15,20)) + 
    xlab(paste('PC1', round(cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
    ylab(paste('PC2', round(cumsum(pcs.props)[2] - cumsum(pcs.props)[1], digits = 3), 
               sep = ' ')) +
    # scale_color_viridis_d() +
    geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.5, size = 0.25) +
    geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.5, size = 0.25) + 
    scale_color_manual(values = cell.type.color.palette, guide = F) +
    theme(legend.position = 'top',
          legend.spacing = unit(0, 'in')) +
      ggrepel::geom_text_repel(segment.color = NA,
                               point.padding = 0.1, show.legend = F) +
    ggprism::theme_prism(base_size = 7)

panel.save('eric.atac', 'hsc_lin_pca')

# print top contibutors per PC
pca.out.contributions %>%
  group_by(pc) %>%
  filter(pc %in% c("PC1","PC2")) %>% 
  select(pc, rel.contrib, tx) %>% 
  # mutate(contrib = abs(contrib)) %>% 
  top_n(5, wt = rel.contrib) %>% 
  arrange(pc, -rel.contrib)
```

```{r}
library(uwot)

set.seed(234)

pca_umap <- as.data.frame(umap(pca.out, n_neighbors = 5, learning_rate = 0.5, init = "random"))

rownames(pca_umap) <- pca.out$sample

pca_umap %>% 
  rownames_to_column('sample') %>% 
  merge(chromvar.col.data %>% rownames_to_column('sample'), by = 'sample') -> uwot.gencode.plot

ggplot(uwot.gencode.plot %>% mutate(cell.type = factor(cell.type, levels = cell.type.order)), 
       aes(V1, 
           V2, 
           color = cell.type, #shape = lineage,
           label = cell.type)) +
  geom_point(size = rel(2.5)) +
  ylab('U2') + 
  xlab('U1') +
  geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.5, size = 0.25) + 
  geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.5, size = 0.25) + 
  scale_color_manual(values = cell.type.color.palette, guide = F) +
  theme(legend.position = 'top',
        legend.spacing = unit(0, 'in')) +
    ggrepel::geom_text_repel(segment.color = NA,
                             point.padding = 0.1, show.legend = F) +
  ggprism::theme_prism(base_size = 7)
panel.save('eric.atac', 'hsc_lin_umap')

```

```{r}
# hsc_only_mpl <- read_tsv(file.path(output.data.dir, 'eric.atac', 'hsc_only_mpl.bed'),
#                          col_names = c('chr', 'start', 'end'))

hsc_only_mpl.great <- read_tsv(file.path(output.data.dir, 'eric.atac', 'hsc_only_mpl.great.out.tsv'), skip = 3) %>% 
  drop_na() 
mpp_only_mpl.great <- read_tsv(file.path(output.data.dir, 'eric.atac', 'mpp_only_mpl.great.out.tsv'), skip = 3) %>% 
  drop_na() 

hsc_only_mpl.great %>% 
  filter(!ID %in% mpp_only_mpl.great$ID) %>% 
  top_n(20, -BinomFdrQ) -> hsc_only_mpl.great.filt


hsc_only_mpl.great.filt %>% 
  ggplot(aes(reorder(Desc, -BinomFdrQ), -log10(BinomFdrQ))) + 
  geom_col() + 
  xlab('') +
  coord_flip() + 
  ggprism::theme_prism(base_size = 10)

# mpp_only_mpl <- read_tsv(file.path(output.data.dir, 'eric.atac', 'mpp_only_mpl.bed'),
#                          col_names = c('chr', 'start', 'end'))
mpp_only_mpl.great %>% 
  filter(!ID %in% hsc_only_mpl.great$ID) %>% 
  top_n(20, -BinomFdrQ) ->mpp_only_mpl.great.filt

mpp_only_mpl.great.filt %>% 
  top_n(4, -BinomFdrQ) %>% 
  select(Desc, BinomFdrQ)


mpp_only_mpl.great.filt %>% 
  ggplot(aes(reorder(Desc, -BinomFdrQ), -log10(BinomFdrQ))) + 
  geom_col() + 
  xlab('') +
  coord_flip() + 
  ggprism::theme_prism(base_size = 10)

```

```{r}
hsc_peaks %>% 
  merge(mpp_peaks, by = c('chr', 'start', 'end', 'idk')) -> hsc_mpp_peaks



chromvar.counts.wide %>% 
  merge(hsc_only_mpl, by = c('chr', 'start', 'end'))

chromvar.counts.wide %>% 
  # merge(hsc_mpp_peaks, by = c('chr', 'start', 'end')) %>% 
  # filter(grepl('TSS', annotation)) %>% 
  select(chr, start, end, gene, annotation, contains('HSC'), contains('MPP')) -> hsc_mpp_tss_peaks_counts

# hsc_mpp_tss_peaks_counts %>% 
  
hsc_only_mpl.great.filt %>% 
  select(Desc, Genes) %>% 
  mutate(Genes = as.list(strsplit(Genes, ','))) %>% 
  unnest(Genes) -> tmp.df


chromvar.counts.wide %>%
  # filter(annotation == 'Intergenic') %>%
  # merge(tmp.df %>% filter(Desc == 'definitive erythrocyte differentiation'), by.x = 'gene', by.y = 'Genes') %>% 
  filter(HSC_jk009 == 0 & HSC_L1 == 0) %>% 
  unite(col = 'gene', sep = '_', c('gene', 'start', 'annotation')) %>% 
  select(gene, contains('_')) %>% 
  mutate(across(contains('_'), ~scale(log(.x + 1), center = T))) %>% 
  column_to_rownames('gene') %>% 
  pheatmap(show_rownames = F)


chromvar.counts.wide %>% 
  filter(MPP_ATAC33 == 0 & MPP_L1 == 0)
  
  
hsc_mpp_tss_peaks_counts %>% 
  gather(sample, count, -chr:-gene) %>% 
  separate(sample, sep = '_', into = c('celltype', NA)) %>% 
  group_by(gene, celltype) %>% 
  summarize(mean_count = mean(count)) %>% 
  spread(celltype, mean_count) %>% 
  mutate(log2FoldChange = log2((MPP+1)/(HSC+1))) %>% 
  arrange(-log2FoldChange) %>% 
  filter(abs(log2FoldChange) > 1) -> hsc_mpp_tss_peaks_diff


msig.df <- 
  msigdbr(species = 'Mus musculus') %>% 
  select(gene_symbol, gs_name) %>% 
  split(x = .$gene_symbol, f = .$gs_name)

de.seq <- 
  hsc_mpp_tss_peaks_diff %>%
  mutate(rank = as.double(log2FoldChange),
         Gene = as.character(gene)) %>% 
  select(Gene, rank) 

de.seq.rnk <- 
  de.seq$rank
de.seq.rnk <- 
  setNames(de.seq$rank, de.seq$Gene)

# run the GSEA implementation on the hallmark sets supplemented with custom sets
print('fgsea')
de.seq.fgsea.res <- 
  fgseaMultilevel(pathways = msig.df, 
        stats = de.seq.rnk)

print('padj filter and clean names')
# convert to a tidy format, clean the names for display
de.seq.fgsea.df <-
  as_tibble(de.seq.fgsea.res) %>%
  filter(padj < 0.1) %>%
  mutate(pathway = gsub('_', ' ', pathway))

  

```

